config/routes.rb
PostcardAlbum::Application.routes.draw do

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  match 'kontakt' => 'contact#index', as: :contact

  match 'zestawy/dodaj_do_zestawu' => 'postcard_sets#add_to_set', as: :add_to_set
  match 'zestawy/aktualny_zestaw' => 'postcard_sets#current_set', as: :current_set

  match '/publishers/:id' => redirect('/wydawcy/%{id}')
  match '/postcards/:id' => redirect('/widokowki/%{id}')
  match '/tags/:id' => redirect('/tagi/%{id}')

  resources :user_sessions
  resources :tags, path: 'tagi'
  resources :newsletter_accounts, path: 'newsletter', path_names: { new: 'zapisz' }

  scope path_names: { new: 'dodaj', edit: 'edytuj' } do
    resources :users, path: 'uzytkownicy'
    resources :publishers, path: 'wydawcy'
    resources :postcards, path: 'widokowki'
    resources :postcard_sets, path: 'zestawy'
    resources :newsletter_messages, path: 'powiadomienia'
  end

  match '/postcards/images/:id/:style.:format' => redirect('/widokowki/zdjecia/%{id}/%{style}.%{format}')
  match '/widokowki/zdjecia/:id/:style.:format' => 'images#show'

  root :to => 'index#index'

end

app/models/postcard_set.rb
class PostcardSet < ActiveRecord::Base

  has_many :postcard_set_elements
  has_many :postcards, through: :postcard_set_elements

  validates_presence_of :description, :title
  validates_inclusion_of :show_abverse, in: [true, false]
  validates_size_of :title, maximum: 255

  accepts_nested_attributes_for :postcard_set_elements, allow_destroy: true

  cattr_reader :per_page
  @@per_page = 4

  include PostcardAlbum::NormalizedUrls

  def to_param
    "#{id}-#{to_permalink(title)}"
  end

  def self.search(params)
    PostcardSet.order('id DESC').paginate(page: params[:page])
  end

end

app/controllers/postcard_sets_controller.rb
class PostcardSetsController < ApplicationController

  POSTCARD_SET_IDS_KEY = :postcard_set_ids

  def index
    @postcard_sets = PostcardSet.search(params)
  end

  def new
    @postcard_set = PostcardSet.new
    init_elements_from_session
  end

  def create
    @postcard_set = PostcardSet.new(params[:postcard_set])

    if @postcard_set.save
      flash[:notice] = t :postcard_set_was_created
      redirect_to(@postcard_set)
    else
      render action: 'new'
    end
  end

  def edit
    @postcard_set = PostcardSet.find(params[:id])
  end

  def update
    @postcard_set = PostcardSet.find(params[:id])

    if @postcard_set.update_attributes(params[:postcard_set])
      flash[:notice] = t :postcard_set_was_updated
      redirect_to(@postcard_set)
    else
      render action: 'edit'
    end
  end

  def destroy
    @postcard_set = PostcardSet.find(params[:id])
    @postcard_set.destroy

    redirect_to(postcard_sets_url)
  end

  def show
    @postcard_set = PostcardSet.find(params[:id])
  end

  # ajax requests

  def add_to_set
    postcard_set_ids = session[POSTCARD_SET_IDS_KEY] || session[POSTCARD_SET_IDS_KEY] = []
    if params[:include_in_set] =~ /^true$/i
      postcard_set_ids << params[:postcard_id].to_i
    else
      postcard_set_ids.delete(params[:postcard_id].to_i)
    end
    render json: postcard_set_ids.size
  end

  def current_set
    render json: session[POSTCARD_SET_IDS_KEY] || []
  end

  private 

  def init_elements_from_session
    session[POSTCARD_SET_IDS_KEY].each_with_index do |postcard_id, i|
      postcard = Postcard.find(postcard_id)
      element = @postcard_set.postcard_set_elements.build(order_number: i)
      element.postcard = postcard
    end
    session[POSTCARD_SET_IDS_KEY].clear
  end

end

app/views/postcard_sets/_form.html.haml
- content_for :head do
  :javascript
    $(document).ready(function() {
      Shadowbox.init();
      initTinyMCE('#{I18n.locale}');
    });

= form_for(@postcard_set, :html => { :multipart => true }) do |f|
  = render partial: '/error_messages', locals: { e: @postcard_set.errors }
  .field
    = f.label :title, t('activerecord.attributes.postcard_set.title')
    = f.text_field :title, rows: 20, class: 'form-full-width'
  .field
    = f.label :description, t('activerecord.attributes.postcard_set.description')
    = f.text_area :description, rows: 20, class: 'form-full-width'
  .field
    = f.label :show_abverse, "#{t('activerecord.attributes.postcard_set.show_abverse')}?"
    .postcard-set-images
      = f.radio_button :show_abverse, true
      - @postcard_set.postcard_set_elements.each do |element|
        = render partial: '/gallery_shadowbox', locals: { postcard: element.postcard, gallery_name: 'postcards', image_parameters: { class: 'small-thumbnail' } }
    .postcard-set-images
      = f.radio_button :show_abverse, false
      - @postcard_set.postcard_set_elements.each do |element|
        = render partial: '/gallery_shadowbox', locals: { abverse: false, postcard: element.postcard, gallery_name: 'postcards', image_parameters: { class: 'small-thumbnail' } }
  .field.clear
    = f.fields_for :postcard_set_elements do |builder|
      = builder.hidden_field :id
      = builder.hidden_field :postcard_id
      = builder.hidden_field :order_number
  = f.submit button_label, :class => 'button'

app/views/postcard_sets/_postcard_set.html.haml
.postcard-set
  %h3= link_to postcard_set.title, postcard_set
  %span.date-added
    = date_added(postcard_set.created_at)
  - if current_user
    %p
      = link_to t(:v_edit), edit_postcard_set_path(postcard_set), class: :important
      = link_to t(:v_delete), postcard_set, method: :delete, confirm: t(:v_delete_confirmation), class: :important
  .images
    - postcard_set.postcards.each do |postcard|
      = render partial: '/gallery_shadowbox', locals: { abverse: postcard_set.show_abverse, postcard: postcard, gallery_name: "gallery-#{postcard_set.id}" }
.clear
%hr

app/views/postcard_sets/edit.html.haml
%h1 Edytuj zestaw widokówek

= render :partial => 'form', :locals => { :button_label => t(:v_edit) }

#bottom-navigation
  = link_to 'Pokaż edytowany zestaw', @postcard_set
  = link_to 'Lista zestawów widokówek', postcard_sets_path

app/views/postcard_sets/index.html.haml
- content_for :head do
  :javascript
    $(document).ready(function() {
      Shadowbox.init();
    });

.pagination
  = will_paginate @postcard_sets, link_separator: ' &nbsp; '
  %hr
= render @postcard_sets
.pagination
  = will_paginate @postcard_sets, link_separator: ' &nbsp; '

app/views/postcard_sets/new.html.haml
%h2 Dodaj zestaw widokówek

= render partial: 'form', locals: { button_label: t(:v_add) }

#bottom-navigation
  = link_to 'Lista zestawów widokówek', postcard_sets_path

app/views/postcard_sets/show.html.haml
- content_for :head do
  :javascript
    $(document).ready(function() {
      Shadowbox.init();
    });

%h3
  = @postcard_set.title

= @postcard_set.description.html_safe

- @postcard_set.postcards.each_with_index do |postcard, i|
  .postcard-set-wrapper
    .postcard-set-image
      = render partial: '/gallery_shadowbox', locals: { abverse: @postcard_set.show_abverse, postcard: postcard, gallery_name: 'postcard' }
    .postcard-set-image-description
      %p
        #{i + 1}
        = link_to postcard.name, postcard
      %p
        Widokówka z roku
        = postcard.year
      %p.small
        Dodano
        = date_added(postcard.created_at)
  .clear
- if current_user
  %p
    = link_to t(:v_edit), edit_postcard_set_path(@postcard_set), class: 'important'
    = link_to t(:v_delete), @postcard_set, method: :delete, confirm: t(:v_delete_confirmation), class: 'important'
#bottom-navigation
  = link_to 'Lista zestawów widokówek', postcard_sets_path