config/routes.rb
PostcardAlbum::Application.routes.draw do

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  match 'kontakt' => 'contact#index', as: :contact

  match 'zestawy/dodaj_do_zestawu' => 'postcard_sets#add_to_set', as: :add_to_set
  match 'zestawy/aktualny_zestaw' => 'postcard_sets#current_set', as: :current_set

  match '/publishers/:id' => redirect('/wydawcy/%{id}')
  match '/postcards/:id' => redirect('/widokowki/%{id}')
  match '/tags/:id' => redirect('/tagi/%{id}')

  resources :user_sessions
  resources :tags, path: 'tagi'
  resources :newsletter_accounts, path: 'newsletter', path_names: { new: 'zapisz' }

  scope path_names: { new: 'dodaj', edit: 'edytuj' } do
    resources :users, path: 'uzytkownicy'
    resources :publishers, path: 'wydawcy'
    resources :postcards, path: 'widokowki'
    resources :postcard_sets, path: 'zestawy'
    resources :newsletter_messages, path: 'powiadomienia'
  end

  match '/postcards/images/:id/:style.:format' => redirect('/widokowki/zdjecia/%{id}/%{style}.%{format}')
  match '/widokowki/zdjecia/:id/:style.:format' => 'images#show'

  root :to => 'index#index'

end

app/models/postcard.rb
class Postcard < ActiveRecord::Base

  acts_as_taggable

  has_many :images, -> { order 'type_of_image' }, dependent: :destroy
  has_many :postcard_set_elements
  has_many :postcard_sets, through: :postcard_set_elements

  belongs_to :publisher

  validates_presence_of :description,
                        :name,
                        :year
  validates_inclusion_of :is_horizontal, in: [true, false]
  validates_size_of :name, maximum: 255
  validates_numericality_of :year, only_integer: true, greater_than: 1800, less_than: 2000

  cattr_reader :per_page
  @@per_page = 12

  accepts_nested_attributes_for :images, allow_destroy: true

  scope :limited, -> (lim) { limit(lim) }
  scope :horizontal, -> { where(is_horizontal: true) }
  scope :most_interesting, -> { horizontal.where(showable_on_main: true).order("created_at") }

  include PostcardAlbum::NormalizedUrls

  def to_param
    "#{id}-#{to_permalink(name)}"
  end

  def is_horizontal
    return true if self[:is_horizontal].nil?
    self[:is_horizontal]
  end

  def is_horizontal?
    is_horizontal
  end

  def orientation
    return :horizontal if is_horizontal?
    :vertical
  end

  def abverse_image
    find_image(Image::IMAGE_TYPES[0])
  end

  def reverse_image
    find_image(Image::IMAGE_TYPES[1])
  end

  def self.search(params)
    relation = Postcard.order('created_at DESC')
    if params[:tag]
      relation = relation.tagged_with(params[:tag])
    end
    relation.paginate(page: params[:page])
  end

  private

  def find_image(image_type)
    Image.where({ postcard_id: id, type_of_image: image_type }).first
  end

end

# == Schema Information
#
# Table name: postcards
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  description   :text
#  created_at    :datetime
#  updated_at    :datetime
#  is_horizontal :boolean
#  latitude      :string(255)
#  longitude     :string(255)
#  year          :integer
#  publisher_id  :integer
#

app/controllers/postcards_controller.rb
class PostcardsController < ApplicationController

  before_action :set_navigation
  before_action :seed_publishers, :only => [:new, :edit]

  def index
    @postcards = Postcard.search(params)
  end

  def show
    @postcard = Postcard.find(params[:id])
  end

  def new
    @postcard = Postcard.new
    @postcard.images.build
  end

  def edit
    @postcard = Postcard.find(params[:id])
  end

  def create
    @postcard = Postcard.new(params[:postcard])

    if @postcard.save
      flash[:notice] = t :postcard_was_created
      redirect_to(@postcard)
    else
      seed_publishers
      render :action => "new"
    end
  end

  def update
    @postcard = Postcard.find(params[:id])

    if @postcard.update_attributes(params[:postcard])
      flash[:notice] = t :postcard_was_updated
      redirect_to(@postcard)
    else
      seed_publishers
      render :action => "edit"
    end
  end

  def destroy
    @postcard = Postcard.find(params[:id])
    @postcard.destroy

    redirect_to(postcards_url)
  end

  
  private

  def set_navigation
    # TODO Rails3
    # current_navigation :postcards    
  end

  def seed_publishers
    @publishers = Publisher.find_all_combobox || []
  end

end

app/helpers/postcards_helper.rb
module PostcardsHelper
  
  def link_to_add_image_fields(f, options)
    image = f.object.images.build 
    fields = f.fields_for(:images, image, :child_index => "new_image") do |builder|
      render :partial => 'image_fields', :locals => { :f => builder, :editable => options[:editable] }
    end
    link_to options[:name], '#', onclick: "addImageFields(this, \"#{escape_javascript(fields)}\")"
  end
  
  def draw_google_map(postcard, map_clicable)
    latitude = postcard.latitude || -1
    longitude = postcard.longitude || -1
    
    # TODO get rid of double assignment
    latitude = -1 if latitude.blank?
    longitude = -1 if longitude.blank?
    
    "drawGoogleMap(#{latitude}, #{longitude}, #{map_clicable});"
  end

end

app/views/postcards/_form.html.haml
- content_for :head do
  = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false'
  :javascript 
    $(document).ready(function() {
      Shadowbox.init();
      #{draw_google_map @postcard, true}
      initTinyMCE('#{I18n.locale}');
      initTags('#{tags_path}.json');
    });

= form_for(@postcard, :html => { :multipart => true }) do |f|
  = render partial: '/error_messages', locals: { e: @postcard.errors }
  .field
    = f.label :name, t('activerecord.attributes.postcard.name')
    = f.text_field :name, class: 'form-full-width'
  .field
    = f.label :description, t('activerecord.attributes.postcard.description')
    = f.text_area :description, rows: 20, class: 'form-full-width'
  .field
    = f.label :is_horizontal, t('activerecord.attributes.postcard.is_horizontal')
    = f.check_box :is_horizontal
  .field
    = f.label :showable_on_main, t('activerecord.attributes.postcard.showable_on_main')
    = f.check_box :showable_on_main
  .field
    = f.label :year, t('activerecord.attributes.postcard.year')
    = f.text_field :year, class: 'form-full-width'
  .field
    = f.label :publisher_id, t('activerecord.attributes.postcard.publisher_id')
    = f.select :publisher_id, @publishers, include_blank: true, class: 'form-full-width'
  .field
    = f.fields_for :images do |builder|
      = render :partial => 'image_fields', locals: { f: builder, editable: editable }
    = link_to_add_image_fields  f, {name: 'Dodaj kolejne zdjęcie', editable: true }
  .field
    = f.label :tag_list, t('activerecord.attributes.postcard.tags')
    = f.text_field :tag_list, class: 'form-full-width'
  .field
    = f.label :longitude, 'Miejsce na mapie'
    #map
    = f.hidden_field :latitude, :id => 'latitude'
    = f.hidden_field :longitude, :id => 'longitude'
  = f.submit button_label, :class => 'button'

app/views/postcards/_image_fields.html.haml
%p.image_fields
  = f.label :type_of_image, t('activerecord.attributes.postcard.images')
  - unless editable
    = f.select :type_of_image, Image::IMAGE_TYPES
    = link_to f.object.image.url(f.object.normal_style), :class => 'lightbox', :rel => 'shadowbox[postcards]' do
      = image_tag(f.object.image.url(f.object.thumbnail_style))
  - else
    = f.select :type_of_image, Image::IMAGE_TYPES
    = f.file_field :image
  = f.hidden_field :_destroy
  = link_to t(:v_delete), '#', onclick: 'removeImage(this)'


app/views/postcards/_postcard.html.haml
.postcard
  %h3= link_to postcard.name, postcard
  %span.date-added
    = date_added(postcard.created_at)
  - if current_user
    %p
      = link_to t(:v_edit), edit_postcard_path(postcard), :class => :important
      = link_to t(:v_delete), postcard, :method => :delete, :confirm => t(:v_delete_confirmation), :class => :important
      = check_box_tag "postcard-set-checkbox-#{postcard.id}", postcard.id, false, class: "postcard-set-checkbox"
  %p
    = render partial: '/gallery_shadowbox', locals: { postcard: postcard }

app/views/postcards/_postcard_details.html.haml
- content_for :head do
  :javascript
    $(document).ready(function() { 
      Shadowbox.init();
    });
  = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false'
  :javascript
    $(document).ready(function() { 
      #{unless p.longitude.blank?
        draw_google_map p, false
      end}
    });

%h3.postcard-heading
  = p.name

= p.description.html_safe

%p
  Widokówka została wydana w #{p.year} roku 
  - if p.publisher
    przez wydawcę #{link_to p.publisher.name, publisher_path(p.publisher)}.

%div
  = render :partial => '/postcards/postcard_lightbox', :locals => { :images => p.images }

- unless p.postcard_sets.empty?
  %h3 Zestawy
  %ul.postcard-sets
    - p.postcard_sets.each do |set|
      %li
        = link_to set.title, set
    
- unless p.longitude.blank?
  #map

- if current_user
  %p
    = link_to t(:v_edit), edit_postcard_path(@postcard), class: 'important'
    = link_to t(:v_delete), @postcard, method: :delete, confirm: t(:v_delete_confirmation), class: 'important'

app/views/postcards/_postcard_lightbox.html.haml
#postcard-images
  - images.each do |i|
    =link_to i.image.url(i.normal_style), {class: 'lightbox', rel: 'shadowbox[gallery]' } do
      =image_tag i.image.url(i.thumbnail_style)

app/views/postcards/edit.html.haml
%h1 Edytuj widokówkę

= render :partial => 'form', :locals => { :button_label => t(:v_edit), :editable => false }

#bottom-navigation
  = link_to 'Pokaż edytowaną widokówkę', @postcard |
  = link_to 'Lista widokówek', postcards_path

app/views/postcards/index.html.haml
- content_for :head do
  :javascript
    $(document).ready(function() {
      Shadowbox.init();
    });
  - if current_user
    :javascript
      $(document).ready(function() {
        populateChecboxesInSet('#{current_set_path}');
        attachPostcardSetsRelatedEvent('#{add_to_set_path}');
      });

.pagination
  = will_paginate @postcards, link_separator: ' &nbsp; '
  %hr
- @postcards.each_slice(3) do |slice|
  = render slice
  .clear
  %hr
.pagination
  = will_paginate @postcards, link_separator: ' &nbsp; '

app/views/postcards/new.html.haml
%h2 Dodaj widokówkę

= render :partial => 'form', :locals => { :button_label => t(:v_add), :editable => true }

#bottom-navigation
  = link_to 'Lista widokówek', postcards_path

app/views/postcards/show.html.haml
= render :partial => 'postcard_details', :locals => { :p => @postcard }
#bottom-navigation
  = link_to 'Lista widokówek', postcards_path